//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgpManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NgpdbmsEntities : DbContext
    {
        public NgpdbmsEntities()
            : base("name=NgpdbmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ngp_contractor> ngp_contractor { get; set; }
        public virtual DbSet<NgpBarangay> NgpBarangays { get; set; }
        public virtual DbSet<NgplocationBarangay> NgplocationBarangays { get; set; }
        public virtual DbSet<NgplocationMunicipality> NgplocationMunicipalities { get; set; }
        public virtual DbSet<NgpLog> NgpLogs { get; set; }
        public virtual DbSet<NgpMaintenanceMode> NgpMaintenanceModes { get; set; }
        public virtual DbSet<NgpMunicipality> NgpMunicipalities { get; set; }
        public virtual DbSet<NgpPosition> NgpPositions { get; set; }
        public virtual DbSet<NgpRole> NgpRoles { get; set; }
        public virtual DbSet<NgpUpload> NgpUploads { get; set; }
        public virtual DbSet<NgpUser> NgpUsers { get; set; }
        public virtual DbSet<NgpYear> NgpYears { get; set; }
    }
}
