//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgpManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgpLoginLog
    {
        public int Id { get; set; }
        public Nullable<int> LoginId { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string RoleName { get; set; }
        public System.DateTime LoginTime { get; set; }
        public System.DateTime LogoutTime { get; set; }
    }
}
